### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by Jubeki**
I updated, fixed, removed and created things in the project so that it is more consistent and easier to work with. In this part, I concentrated on all page except the admin section. This section will come in a later update.

What did I do:
- UserController is now named ProfileController
- The route /profile shows and updates now the Profile
- The view was renamed from home.blade.php to profile.blade.php
- A list of registerable Camps can now be get with Camp::getRegisterableCamps() (there are more functions)
- I removed also unnecessary methods/variables/files and co.
- The Controllers are mostly commented on
- The CampController manages now interaction from the user with a camp
- CampUserController will be used for administration of the user
- I fixed some bugs and spelling mistakes but I think there are still more which I didn't test

The last thing I did was format all files so that they are more readable and maintainable.

I hope this is an update so that more people can work on campy.

### CODE REVIEW

**Comment by Jubeki** [comment]
I thought of doing smaller PR but then I couldn't update the whole project because it would be many changes in very different contexts.
So I did for single changes a commit so that each of the commits is revertible.
But yeah future changes will be in smaller PR.
I can also split it in smaller PR just by moving single commits to other branches and therefore smaller PR if you like this more.

**Comment by minthemiddle** [comment]
@Jubeki Creating PRs is a skill of its own, so no worries.

**Comment by Jubeki** [comment]
I created multiple pull request that split this into smaller.
Before merging this pull request I could look at the code and maybe split it more.

**Comment by minthemiddle** [comment]
@Jubeki and me manually went through the whole PR and it is okay to merge everything.

**Pull request merged**
